# Generated by Django 5.1.2 on 2024-10-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pridaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={},
        ),
    ]
